# Generated by Django 3.2.2 on 2021-05-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_remove_aluno_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
